from typing import List
import datetime as dt


# If comparisons will be required, this will need to change to an OrderedDict
output_fields = {
    "platformId": str,
    "platform": str,
    "date": dt.datetime,
    "updated": dt.datetime,
    "type": str,
    "title": str,
    "caption": str,
    "description": str,
    "message": str,
    "expandedLinksOriginal": List[str],
    "expandedLinksExpanded": List[str],
    "link": str,
    "postUrl": str,
    "subscriberCount": int,
    "score": float,
    "mediaType": List[str],
    "mediaUrl": List[str],
    "mediaHeight": List[int],
    "mediaWidth": List[int],
    "mediaFull": List[str],
    "actualLikeCount": int,
    "actualShareCount": int,
    "actualCommentCount": int,
    "actualLoveCount": int,
    "actualWowCount": int,
    "actualHahaCount": int,
    "actualSadCount": int,
    "actualAngryCount": int,
    "actualThankfulCount": int,
    "actualCareCount": int,
    "expectedLikeCount": int,
    "expectedShareCount": int,
    "expectedCommentCount": int,
    "expectedLoveCount": int,
    "expectedWowCount": int,
    "expectedHahaCount": int,
    "expectedSadCount": int,
    "expectedAngryCount": int,
    "expectedThankfulCount": int,
    "expectedCareCount": int,
    "accountId": str,
    "accountName": str,
    "accountHandle": str,
    "accountProfileImage": str,
    "accountSubscriberCount": int,
    "accountUrl": str,
    "accountPlatform": str,
    "accountPlatformId": str,
    "accountAccountType": str,
    "accountPageAdminTopCountry": str,
    "accountVerified": bool,
    "imageText": str,
    "videoLengthMS": int,
    "liveVideoStatus": str,
    "newId": str,
    "id": str
}

output_history_fields = {
    "historyActualTimestep": str,  # todo: check this
    "historyActualDate": dt.datetime,  # todo: check this
    "historyActualScore": int,
    "historyActualLikeCount": int,
    "historyActualShareCount": int,
    "historyActualCommentCount": int,
    "historyActualLoveCount": int,
    "historyActualWowCount": int,
    "historyActualHahaCount": int,
    "historyActualSadCount": int,
    "historyActualAngryCount": int,
    "historyActualThankfulCount": int,
    "historyActualCareCount": int,
    "historyExpectedLikeCount": int,
    "historyExpectedShareCount": int,
    "historyExpectedCommentCount": int,
    "historyExpectedLoveCount": int,
    "historyExpectedWowCount": int,
    "historyExpectedHahaCount": int,
    "historyExpectedSadCount": int,
    "historyExpectedAngryCount": int,
    "historyExpectedThankfulCount": int,
    "historyExpectedCareCount": int
}
