## set to null for any param that's not required for your search
## "Post" endpoint is designed specfically for scraping particular post(s) with post id(s) 
token: ""                                          #[string][default: ""][REQUIRED] <API Token could be acquired from your dashboard>
endpoint: "post"                                   #[default: "post"]
ids: ""                                            #[string] e.g. "123,456" 
output_filename: null                              #[string][default: <datetime.NOW>.csv] e.g. "output.csv"
log: false                                         #[boolean][default: false]
history: false                                     #[boolean][default: false] 
togbq: false                                       #[booelan][default: false]                                  
bq_credential: "xxx.json"                          #service account credential file
bq_table_id: "dataset_id.table_id "                #dataset_id.table_id on BQ